application: thecapturedproject
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/orders
  script: _go_app
  secure: always
  login: admin
- url: /api/.*
  script: _go_app
  secure: always
- url: /(.*\.js)
  static_files: assets/\1
  upload: assets/.*\.js
  mime_type: text/javascript; charset=UTF-8
  secure: always
  expiration: "30d"
- url: /
  static_files: assets/index.html
  upload: assets/index.html
  mime_type: text/html; charset=UTF-8
  secure: always
  expiration: "1m"
- url: /orders/
  static_files: assets/orders/index.html
  upload: assets/orders/index\.html
  mime_type: text/html; charset=UTF-8
  secure: always
  login: admin
  expiration: "1m"
- url: /orders
  static_files: assets/orders/index.html
  upload: assets/orders/index\.html
  mime_type: text/html; charset=UTF-8
  secure: always
  login: admin
  expiration: "1m"
- url: /(.*)/
  static_files: assets/\1/index.html
  upload: assets/.*\.html
  mime_type: text/html; charset=UTF-8
  secure: always
  expiration: "1m"
- url: /(.*)
  static_files: assets/\1/index.html
  upload: assets/.*\.html
  mime_type: text/html; charset=UTF-8
  secure: always
  expiration: "1m"

error_handlers:
  - file: assets/error.html

skip_files:
- ^(.*/)?\..*$
- ^src/.*$
- ^etc/.*$
- ^misc/.*$
- '^[^/]*\.js$'
- ^Makefile$
- ^node_modules/.*$
- ^package\.json$
- ^(.*/)?README\.md$
- ^.*\.sublime-project$
- ^.*\.sublime-workspace$
